package guilhermeteixeira.lanchonete.view;


import guilhermeteixeira.lanchonete.model.Lanche;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILHERME
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
    initComponents();
    
    

    jInternalFrameCadastroLanche.setVisible(false);
    jInternalFramePesquisar.setVisible(false);

    setLocationRelativeTo(null);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jInternalFrameCadastroLanche = new javax.swing.JInternalFrame();
        jLabelCadastroLanche = new javax.swing.JLabel();
        jTextFieldCadastroLancheNome = new javax.swing.JTextField();
        jLabelCadastroLanchePreco = new javax.swing.JLabel();
        jTextFieldCadastroLanchePreco = new javax.swing.JTextField();
        jButtonCadastroLancheSalvar = new javax.swing.JButton();
        jButtonCadastroLancheCancelar = new javax.swing.JButton();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarId = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroLanche = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoLanche = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarLanche = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Que Lanche Gostoso");
        setIconImages(null);

        jDesktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane.setPreferredSize(new java.awt.Dimension(600, 400));

        jInternalFramePesquisar.setTitle("Pesquisar Pelo Nome");
        jInternalFramePesquisar.setPreferredSize(new java.awt.Dimension(400, 200));
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarPorNome);

        jLabel1.setText("Selecione a Ação Desejada");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir" }));

        jLabel2.setText("Qual o ID do Lanche");

        jTextFieldPesquisarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarIDActionPerformed(evt);
            }
        });

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarConfirmarActionPerformed(evt);
            }
        });

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFramePesquisarLayout.createSequentialGroup()
                                .addComponent(jButtonPesquisarConfirmar)
                                .addGap(104, 104, 104)
                                .addComponent(jButtonPesquisarCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFramePesquisarLayout.createSequentialGroup()
                                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(49, 49, 49)
                                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarConfirmar)
                    .addComponent(jButtonPesquisarCancelar))
                .addGap(45, 45, 45))
        );

        jDesktopPane.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );

        jInternalFrameCadastroLanche.setMaximumSize(new java.awt.Dimension(0, 0));
        jInternalFrameCadastroLanche.setPreferredSize(new java.awt.Dimension(400, 280));
        jInternalFrameCadastroLanche.setVisible(true);

        jLabelCadastroLanche.setText("Nome do Lanche");

        jTextFieldCadastroLancheNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroLancheNomeActionPerformed(evt);
            }
        });

        jLabelCadastroLanchePreco.setText("Preço");

        jButtonCadastroLancheSalvar.setText("Salvar");
        jButtonCadastroLancheSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroLancheCancelar.setText("Cancelar");
        jButtonCadastroLancheCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroLancheLayout = new javax.swing.GroupLayout(jInternalFrameCadastroLanche.getContentPane());
        jInternalFrameCadastroLanche.getContentPane().setLayout(jInternalFrameCadastroLancheLayout);
        jInternalFrameCadastroLancheLayout.setHorizontalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelCadastroLanchePreco)
                        .addGap(48, 48, 48)
                        .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addComponent(jLabelCadastroLanche)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonCadastroLancheCancelar)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonCadastroLancheSalvar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jInternalFrameCadastroLancheLayout.setVerticalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroLanche))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroLanchePreco))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroLancheSalvar)
                    .addComponent(jButtonCadastroLancheCancelar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jInternalFrameEditarCadastro.setTitle("Edição de Cadastro");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome Do Lanche");

        jTextFieldEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditarNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço");

        jLabel5.setText("ID:");

        jTextFieldEditarId.setEnabled(false);

        jButtonEditarSalvar.setText("Salvar");
        jButtonEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvarActionPerformed(evt);
            }
        });

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonEditarSalvar)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonEditarCancelar))
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEditarNome)
                            .addComponent(jTextFieldEditarPreco)
                            .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroLanche.setText("Lanche");
        jMenuItemCadastroLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroLancheActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroLanche);

        jMenuBar1.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoLanche.setText("Lanche");
        jMenuItemEdicaoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdicaoLancheActionPerformed(evt);
            }
        });
        jMenuEdicao.add(jMenuItemEdicaoLanche);

        jMenuBar1.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarLanche.setText("Lanche");
        jMenuItemPesquisarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarLancheActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarLanche);

        jMenuBar1.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuItemVendasCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasCarrinhoActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBar1.add(jMenuVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jInternalFrameCadastroLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVendasCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVendasCarrinhoActionPerformed

    private void jMenuItemCadastroLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroLancheActionPerformed
         jInternalFrameCadastroLanche.setVisible(true);
        centralizarInternalFrame(jInternalFrameCadastroLanche); 
       
    }//GEN-LAST:event_jMenuItemCadastroLancheActionPerformed

    private void jButtonCadastroLancheCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroLancheNome.setText("");
        jTextFieldCadastroLanchePreco.setText("");
        jInternalFrameCadastroLanche.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroLancheCancelarActionPerformed

    private void jButtonCadastroLancheSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroLancheNome.getText();
        
        if (nome.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Digite o Nome do Lanche, está vazio!");
          } else {
             String preco = jTextFieldCadastroLanchePreco.getText();
             
             if (preco.equals("")){
              JOptionPane.showMessageDialog(rootPane, "O Campo Preço do Lanche, está vazio!");
          } else {
                 try {
                     double precoConvertido = Double.parseDouble(preco);
                     Lanche lanche = new Lanche(nome, precoConvertido);
                     lanche.apresentarLanche();
                     lanche.salvar(nome, precoConvertido);
                                         
                     jTextFieldCadastroLancheNome.setText("");
                     jTextFieldCadastroLanchePreco.setText("");
                     
                     JOptionPane.showMessageDialog(rootPane, "O Lanche "+nome+" Foi Cadastrado Com Sucesso!");
                     
                     
                 } catch (Exception e){
                     JOptionPane.showMessageDialog(rootPane, "Preencha  o Campo Preço do Lanche, apenas com Números e Sepados por Ponto, Não coloque Virgulas!");
                 }
             }
        }
    }
        public JInternalFrame getjInternalFrameCadastroLanche() {
         return jInternalFrameCadastroLanche;
    }//GEN-LAST:event_jButtonCadastroLancheSalvarActionPerformed
 
        public JInternalFrame getJInternalFramePesquisar(){
            centralizarInternalFrame(jInternalFramePesquisar);
             return jInternalFramePesquisar;
}
    private void jMenuItemPesquisarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarLancheActionPerformed
              modelo = new DefaultTableModel();
              jTablePesquisarPorNome.setModel(modelo);
              String nome = JOptionPane.showInputDialog("Informe o Nome do Lanche: ");
              Lanche lanche = new Lanche();
               jInternalFramePesquisar.setVisible(true);
                centralizarInternalFrame(jInternalFramePesquisar);
              ArrayList<Lanche> lanches = lanche.pesquisar(nome);
              System.out.println("Qtd lanches encontrados: " + lanches.size());
              modelo.addColumn("ID");
              modelo.addColumn("Nome");
              modelo.addColumn("Preço");
              
              for (Lanche lancheAux : lanches){
                  modelo.addRow (new Object[]{lancheAux.getId(),lancheAux.getNome(), lancheAux.getPreco()});
                  jTablePesquisarPorNome.setModel(modelo);
                }
                  
                   jInternalFramePesquisar.setVisible(true);
              }


    public JTable getjTablePesquisarPorNome(){
      jInternalFramePesquisar.setVisible(true);
      return jTablePesquisarPorNome;
      
    }//GEN-LAST:event_jMenuItemPesquisarLancheActionPerformed

    private void jTextFieldPesquisarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarIDActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
                // TODO add your handling code here:
                Lanche lanche = new Lanche();
          String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
          System.out.println("Opção selecionada: "+opcao);
          
              int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
              System.out.println("ID Informado:"+idPesquisar);
              if (opcao.equals("Excluir")){
                  lanche.deletar(idPesquisar);
                  JOptionPane.showMessageDialog(rootPane, "O Lanche de ID: "+idPesquisar+ " Foi Deletado com Sucesso!");
                 
                  
                 jComboBoxPesquisarAcao.setSelectedIndex(0);
                 jTextFieldPesquisarID.setText("");
                jInternalFramePesquisar.setVisible(false);   
              }else {  // editar
              jInternalFramePesquisar.setVisible(false);
                            
             Lanche lancheRecuperado = lanche.buscarPorId(idPesquisar);
             
             jTextFieldEditarId.setText(idPesquisar+"");
             jTextFieldEditarNome.setText(lancheRecuperado.getNome());
             jTextFieldEditarPreco.setText(lancheRecuperado.getPreco()+"");
                 
              jInternalFrameEditarCadastro.setVisible(true);
              }
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        
         jInternalFramePesquisar.setVisible(false);
                
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed
           public JInternalFrame getJInternalFrameEditarCadastro(){
               return jInternalFrameEditarCadastro;
               
           }
    private void jTextFieldEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditarNomeActionPerformed

    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        jInternalFrameEditarCadastro.setVisible(false);
        
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldEditarNome.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());
        int id = Integer.parseInt(jTextFieldEditarId.getText());
        
        Lanche lanche = new Lanche();
        lanche.editar(nome, preco, id);
        
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
        
        
    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed

    private void jTextFieldCadastroLancheNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroLancheNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroLancheNomeActionPerformed

    private void jMenuItemEdicaoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoLancheActionPerformed
               // TODO add your handling code here:
                modelo = new DefaultTableModel();
              jTablePesquisarPorNome.setModel(modelo);
              String nome = JOptionPane.showInputDialog("Informe o Nome do Lanche: ");
              Lanche lanche = new Lanche();
               jInternalFramePesquisar.setVisible(true);
                centralizarInternalFrame(jInternalFramePesquisar);
              ArrayList<Lanche> lanches = lanche.pesquisar(nome);
              System.out.println("Qtd lanches encontrados: " + lanches.size());
              modelo.addColumn("ID");
              modelo.addColumn("Nome");
              modelo.addColumn("Preço");
              
              for (Lanche lancheAux : lanches){
                  modelo.addRow (new Object[]{lancheAux.getId(),lancheAux.getNome(), lancheAux.getPreco()});
                  jTablePesquisarPorNome.setModel(modelo);
                }
                  
                   jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemEdicaoLancheActionPerformed
     private void centralizarInternalFrame(JInternalFrame frame) {
     // Força o cálculo do layout interno
     int largura = jDesktopPane.getWidth();
    int altura = jDesktopPane.getHeight();

    int larguraFrame = frame.getWidth();
    int alturaFrame = frame.getHeight();
        int larguraDesktop = 0;

   int x = Math.max((larguraDesktop - larguraFrame) / 2, 0);
        int alturaDesktop = 0;
    int y = Math.max((alturaDesktop - alturaFrame) / 2, 0);
    

    frame.setLocation(x, y);
    }
 private DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroLancheCancelar;
    private javax.swing.JButton jButtonCadastroLancheSalvar;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jInternalFrameCadastroLanche;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastroLanche;
    private javax.swing.JLabel jLabelCadastroLanchePreco;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroLanche;
    private javax.swing.JMenuItem jMenuItemEdicaoLanche;
    private javax.swing.JMenuItem jMenuItemPesquisarLanche;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroLancheNome;
    private javax.swing.JTextField jTextFieldCadastroLanchePreco;
    private javax.swing.JTextField jTextFieldEditarId;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldPesquisarID;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

      
}